# Generated by Django 4.0 on 2026-08-15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("education", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150, unique=True)),
                ("description", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("ACTIVE", "Активен"), ("ARCHIVED", "В архиве")], db_index=True, default="ACTIVE", max_length=16)),
                ("default_monthly_fee", models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ("name",)},
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("full_name", models.CharField(max_length=255)),
                ("phone", models.CharField(blank=True, db_index=True, max_length=32)),
                ("status", models.CharField(choices=[("ACTIVE", "Активен"), ("ARCHIVED", "В архиве")], db_index=True, default="ACTIVE", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ("full_name",)},
        ),
        migrations.AddField(model_name="teacher", name="full_name", field=models.CharField(blank=True, max_length=255)),
        migrations.AddField(model_name="teacher", name="phone", field=models.CharField(blank=True, db_index=True, max_length=32)),
        migrations.AddField(model_name="teacher", name="status", field=models.CharField(choices=[("ACTIVE", "Активен"), ("ARCHIVED", "В архиве")], db_index=True, default="ACTIVE", max_length=16)),
    ]
