# Generated by Django 4.0 on 2026-08-15

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("education", "0002_course_student_teacher_full_name_teacher_phone_and_more")]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150)),
                ("monthly_fee", models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ("status", models.CharField(choices=[("ACTIVE", "Активен"), ("ARCHIVED", "В архиве")], db_index=True, default="ACTIVE", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("course", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="groups", to="education.course")),
                ("teacher", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="groups", to="education.teacher")),
            ],
            options={"ordering": ("name",)},
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("started_at", models.DateField()),
                ("ended_at", models.DateField(blank=True, null=True)),
                ("status", models.CharField(choices=[("ACTIVE", "Активно"), ("ENDED", "Завершено")], db_index=True, default="ACTIVE", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("group", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="enrollments", to="education.group")),
                ("student", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="enrollments", to="education.student")),
            ],
            options={"ordering": ("-started_at", "-pk")},
        ),
        migrations.AddConstraint(model_name="enrollment", constraint=models.UniqueConstraint(condition=models.Q(("status", "ACTIVE")), fields=("student", "group"), name="unique_active_enrollment_per_student_group")),
        migrations.AddConstraint(model_name="enrollment", constraint=models.CheckConstraint(check=models.Q(models.Q(("ended_at__isnull", True), ("status", "ACTIVE")), models.Q(("ended_at__isnull", False), ("status", "ENDED")), _connector="OR"), name="enrollment_status_matches_end_date")),
        migrations.AddConstraint(model_name="enrollment", constraint=models.CheckConstraint(check=models.Q(("ended_at__isnull", True), ("ended_at__gte", django.db.models.expressions.F("started_at")), _connector="OR"), name="enrollment_end_not_before_start")),
    ]
