# Generated by Django 4.0 on 2026-08-15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("education", "0003_group_enrollment_and_more")]

    operations = [
        migrations.CreateModel(name="Schedule", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("weekday", models.PositiveSmallIntegerField(choices=[(0, "Понедельник"), (1, "Вторник"), (2, "Среда"), (3, "Четверг"), (4, "Пятница"), (5, "Суббота"), (6, "Воскресенье")], db_index=True)), ("start_time", models.TimeField()), ("end_time", models.TimeField()), ("is_active", models.BooleanField(db_index=True, default=True)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("group", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="schedules", to="education.group"))], options={"ordering": ("weekday", "start_time")}),
        migrations.CreateModel(name="Lesson", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("date", models.DateField(db_index=True)), ("start_time", models.TimeField()), ("end_time", models.TimeField()), ("status", models.CharField(choices=[("SCHEDULED", "Запланировано"), ("COMPLETED", "Завершено"), ("CANCELLED", "Отменено")], db_index=True, default="SCHEDULED", max_length=16)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("group", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="lessons", to="education.group")), ("schedule", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="lessons", to="education.schedule"))], options={"ordering": ("date", "start_time")}),
    ]
