# Generated by Django 4.0 on 2026-08-16 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0004_schedule_lesson"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("PRESENT", "Присутствовал"), ("ABSENT", "Отсутствовал"), ("LATE", "Опоздал")], db_index=True, max_length=16)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("lesson", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="attendance_records", to="education.lesson")),
                ("student", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="attendance_records", to="education.student")),
            ],
            options={
                "ordering": ("student__full_name",),
            },
        ),
        migrations.AddConstraint(
            model_name="attendance",
            constraint=models.UniqueConstraint(fields=("lesson", "student"), name="unique_attendance_per_lesson_student"),
        ),
    ]
