# Generated by Django 4.0 on 2026-08-16 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('education', '0006_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('PAYMENT_CREATE', 'Создание платежа'), ('PAYMENT_EDIT', 'Изменение платежа'), ('PAYMENT_CANCEL', 'Отмена платежа'), ('ATTENDANCE_CHANGE', 'Изменение посещаемости'), ('ENROLLMENT_CREATE', 'Зачисление ученика'), ('ENROLLMENT_END', 'Завершение обучения'), ('STUDENT_ARCHIVE', 'Архивация ученика'), ('STUDENT_RESTORE', 'Восстановление ученика')], db_index=True, max_length=32)),
                ('target_type', models.CharField(db_index=True, max_length=32)),
                ('target_id', models.PositiveBigIntegerField(db_index=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='accounts.user')),
            ],
            options={
                'verbose_name': 'Запись аудита',
                'verbose_name_plural': 'Журнал аудита',
                'ordering': ('-created_at', '-pk'),
            },
        ),
    ]
