# Generated by Django 4.0 on 2026-08-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('PAYMENT_CREATE', 'Создание платежа'), ('PAYMENT_EDIT', 'Изменение платежа'), ('PAYMENT_CANCEL', 'Отмена платежа'), ('ATTENDANCE_CHANGE', 'Изменение посещаемости'), ('ENROLLMENT_CREATE', 'Зачисление ученика'), ('ENROLLMENT_END', 'Завершение обучения'), ('STUDENT_CREATE', 'Создание ученика'), ('STUDENT_ARCHIVE', 'Архивация ученика'), ('STUDENT_RESTORE', 'Восстановление ученика')], db_index=True, max_length=32),
        ),
    ]
