# Generated by Django 4.0 on 2026-08-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0008_alter_auditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='homework',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='teacher_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='topic',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='schedule',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('PAYMENT_CREATE', 'Создание платежа'), ('PAYMENT_EDIT', 'Изменение платежа'), ('PAYMENT_CANCEL', 'Отмена платежа'), ('ATTENDANCE_CHANGE', 'Изменение посещаемости'), ('ENROLLMENT_CREATE', 'Зачисление ученика'), ('ENROLLMENT_END', 'Завершение обучения'), ('STUDENT_CREATE', 'Создание ученика'), ('STUDENT_ARCHIVE', 'Архивация ученика'), ('STUDENT_RESTORE', 'Восстановление ученика'), ('LESSON_CREATE', 'Создание занятия'), ('LESSON_EDIT', 'Изменение занятия'), ('LESSON_CANCEL', 'Отмена занятия'), ('LESSON_COMPLETE', 'Завершение занятия'), ('LESSON_RESCHEDULE', 'Перенос занятия'), ('LESSON_REPORT', 'Отчёт о занятии'), ('SCHEDULE_CREATE', 'Создание расписания'), ('SCHEDULE_EDIT', 'Изменение расписания'), ('SCHEDULE_DEACTIVATE', 'Деактивация расписания'), ('SCHEDULE_GENERATE', 'Генерация занятий')], db_index=True, max_length=32),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('group', 'date', 'start_time'), name='unique_lesson_group_date_time'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(condition=models.Q(('schedule__isnull', False)), fields=('schedule', 'date'), name='unique_lesson_schedule_date'),
        ),
    ]
