# Generated by Django 4.0 on 2026-08-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0009_lesson_homework_lesson_teacher_note_lesson_topic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('PAYMENT_CREATE', 'Создание платежа'), ('PAYMENT_EDIT', 'Изменение платежа'), ('PAYMENT_CANCEL', 'Отмена платежа'), ('ATTENDANCE_CHANGE', 'Изменение посещаемости'), ('ENROLLMENT_CREATE', 'Зачисление ученика'), ('ENROLLMENT_END', 'Завершение обучения'), ('STUDENT_CREATE', 'Создание ученика'), ('STUDENT_ARCHIVE', 'Архивация ученика'), ('STUDENT_RESTORE', 'Восстановление ученика'), ('LESSON_CREATE', 'Создание занятия'), ('LESSON_EDIT', 'Изменение занятия'), ('LESSON_CANCEL', 'Отмена занятия'), ('LESSON_COMPLETE', 'Завершение занятия'), ('LESSON_RESCHEDULE', 'Перенос занятия'), ('LESSON_REPORT', 'Отчёт о занятии'), ('SCHEDULE_CREATE', 'Создание расписания'), ('SCHEDULE_EDIT', 'Изменение расписания'), ('SCHEDULE_DEACTIVATE', 'Деактивация расписания'), ('SCHEDULE_GENERATE', 'Генерация занятий'), ('COURSE_CREATE', 'Создание курса'), ('COURSE_EDIT', 'Изменение курса'), ('COURSE_STATUS', 'Изменение статуса курса'), ('GROUP_CREATE', 'Создание группы'), ('GROUP_EDIT', 'Изменение группы'), ('GROUP_STATUS', 'Изменение статуса группы'), ('TEACHER_EDIT', 'Изменение преподавателя'), ('TEACHER_STATUS', 'Изменение статуса преподавателя')], db_index=True, max_length=32),
        ),
    ]
