# Generated by Django 4.0 on 2026-08-18 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0010_alter_auditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='source',
            field=models.CharField(choices=[('NORMAL', 'Расписание'), ('OVERRIDE', 'Исключение')], db_index=True, default='NORMAL', max_length=16),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('PAYMENT_CREATE', 'Создание платежа'), ('PAYMENT_EDIT', 'Изменение платежа'), ('PAYMENT_CANCEL', 'Отмена платежа'), ('ATTENDANCE_CHANGE', 'Изменение посещаемости'), ('ENROLLMENT_CREATE', 'Зачисление ученика'), ('ENROLLMENT_END', 'Завершение обучения'), ('STUDENT_CREATE', 'Создание ученика'), ('STUDENT_ARCHIVE', 'Архивация ученика'), ('STUDENT_RESTORE', 'Восстановление ученика'), ('LESSON_CREATE', 'Создание занятия'), ('LESSON_EDIT', 'Изменение занятия'), ('LESSON_CANCEL', 'Отмена занятия'), ('LESSON_COMPLETE', 'Завершение занятия'), ('LESSON_RESCHEDULE', 'Перенос занятия'), ('LESSON_REPORT', 'Отчёт о занятии'), ('SCHEDULE_CREATE', 'Создание расписания'), ('SCHEDULE_EDIT', 'Изменение расписания'), ('SCHEDULE_DEACTIVATE', 'Деактивация расписания'), ('SCHEDULE_GENERATE', 'Генерация занятий'), ('OVERRIDE_CREATE', 'Создание исключения расписания'), ('OVERRIDE_EDIT', 'Изменение исключения расписания'), ('OVERRIDE_DELETE', 'Удаление исключения расписания'), ('COURSE_CREATE', 'Создание курса'), ('COURSE_EDIT', 'Изменение курса'), ('COURSE_STATUS', 'Изменение статуса курса'), ('GROUP_CREATE', 'Создание группы'), ('GROUP_EDIT', 'Изменение группы'), ('GROUP_STATUS', 'Изменение статуса группы'), ('TEACHER_EDIT', 'Изменение преподавателя'), ('TEACHER_STATUS', 'Изменение статуса преподавателя')], db_index=True, max_length=32),
        ),
        migrations.CreateModel(
            name='ScheduleOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('override_type', models.CharField(choices=[('CANCELLED', 'Отменено'), ('RESCHEDULED', 'Перенесено'), ('SUBSTITUTE', 'Замена преподавателя')], db_index=True, max_length=16)),
                ('new_date', models.DateField(blank=True, null=True)),
                ('new_start_time', models.TimeField(blank=True, null=True)),
                ('new_end_time', models.TimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='education.schedule')),
                ('substitute_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='substitute_overrides', to='education.teacher')),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.AddConstraint(
            model_name='scheduleoverride',
            constraint=models.UniqueConstraint(fields=('schedule', 'date'), name='unique_override_per_schedule_date'),
        ),
    ]
