# Generated by Django 4.0 on 2026-08-19 14:50

from django.db import migrations, models
import django.db.models.deletion


def populate_occurrence_and_teacher(apps, schema_editor):
    Lesson = apps.get_model('education', 'Lesson')
    for lesson in Lesson.objects.select_related('group').iterator():
        lesson.teacher_id = lesson.group.teacher_id
        if lesson.schedule_id:
            lesson.occurrence_date = lesson.date
        lesson.save(update_fields=('teacher', 'occurrence_date'))


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0011_lesson_source_alter_auditlog_action_scheduleoverride_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lesson',
            name='unique_lesson_schedule_date',
        ),
        migrations.AddField(
            model_name='lesson',
            name='occurrence_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_lessons', to='education.teacher'),
        ),
        migrations.RunPython(populate_occurrence_and_teacher, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(condition=models.Q(('occurrence_date__isnull', False), ('schedule__isnull', False)), fields=('schedule', 'occurrence_date'), name='unique_lesson_schedule_occurrence'),
        ),
    ]
